import React, { useState } from 'react';
import { useAuth } from './context/AuthContext';
import { Login } from './pages/Login';
import { Register } from './pages/Register';
import { Dashboard } from './pages/Dashboard';
import { WorkflowBuilder } from './pages/Builder';
import { Logs } from './pages/Logs';
import { Profile } from './pages/Profile';
import api from './services/api';
import { 
  LayoutDashboard, Terminal, User, LogOut, Loader2, 
  Menu, X 
} from 'lucide-react';

export const AppContent: React.FC = () => {
  const { user, loading, logout } = useAuth();
  const [authScreen, setAuthScreen] = useState<'login' | 'register'>('login');
  const [activeTab, setActiveTab] = useState<'dashboard' | 'logs' | 'profile' | 'builder'>('dashboard');
  const [editingWorkflowId, setEditingWorkflowId] = useState<string | null>(null);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  // Navigate to Builder
  const handleNavigateToBuilder = (workflowId?: string) => {
    if (workflowId) {
      setEditingWorkflowId(workflowId);
    } else {
      setEditingWorkflowId(null);
    }
    setActiveTab('builder');
  };

  // Create template workflow
  const handleNavigateToTemplates = async (templateId: string) => {
    try {
      // Find default template configuration properties
      let name = 'AI Workflow';
      let description = '';
      let nodes: any[] = [];
      let edges: any[] = [];

      switch (templateId) {
        case 'template_email_summarizer':
          name = 'AI Email Summarizer';
          description = 'Trigger on manual input and generate an AI summary using Gemini.';
          nodes = [
            {
              id: 'trigger-1',
              type: 'manualTrigger',
              position: { x: 100, y: 200 },
              data: {
                label: 'Manual Gmail Trigger',
                description: 'Pass incoming email data fields.',
                config: {
                  payload: {
                    sender: 'newsletter@techweekly.com',
                    subject: 'Weekly AI Innovations Newsletter',
                    body: 'Artificial Intelligence has seen major breakthroughs this week. OpenAI released GPT-5, Anthropic upgraded Claude with longer context, and Google integrated Gemini natively into Android system kernels.'
                  }
                }
              }
            },
            {
              id: 'gemini-1',
              type: 'geminiNode',
              position: { x: 380, y: 200 },
              data: {
                label: 'Gemini AI Summary',
                description: 'Generate concise summaries using Gemini AI.',
                config: {
                  task: 'summarize',
                  prompt: 'Summarize the following email newsletter content. Extract main breakthroughs: "{{trigger.body}}"'
                }
              }
            },
            {
              id: 'email-1',
              type: 'emailNode',
              position: { x: 660, y: 200 },
              data: {
                label: 'Send Summary Email',
                description: 'Send the summarized newsletter text.',
                config: {
                  to: 'me@company.com',
                  subject: 'AI Newsletter Summary: {{trigger.subject}}',
                  body: 'Here is the summary generated by FlowGenius AI:\n\n{{nodes.gemini-1.output}}'
                }
              }
            }
          ];
          edges = [
            { id: 'edge-1', source: 'trigger-1', target: 'gemini-1', animated: true },
            { id: 'edge-2', source: 'gemini-1', target: 'email-1', animated: true }
          ];
          break;

        case 'template_lead_generator':
          name = 'AI Lead Enrichment';
          description = 'Receive webhook payloads, extract keywords and sentiment, and log to Google Sheets.';
          nodes = [
            {
              id: 'trigger-1',
              type: 'webhookTrigger',
              position: { x: 100, y: 200 },
              data: {
                label: 'Webhook Lead Trigger',
                description: 'Receive payload from signup form.',
                config: {}
              }
            },
            {
              id: 'gemini-1',
              type: 'geminiNode',
              position: { x: 380, y: 100 },
              data: {
                label: 'Sentiment Evaluator',
                description: 'Analyze sign-up interest sentiment.',
                config: {
                  task: 'sentiment',
                  prompt: 'Analyze lead review: "{{trigger.comments}}"'
                }
              }
            },
            {
              id: 'gemini-2',
              type: 'geminiNode',
              position: { x: 380, y: 300 },
              data: {
                label: 'Keywords Extractor',
                description: 'Extract product interest tags.',
                config: {
                  task: 'keywords',
                  prompt: 'Extract interest tags: "{{trigger.comments}}"'
                }
              }
            },
            {
              id: 'db-1',
              type: 'dbNode',
              position: { x: 680, y: 200 },
              data: {
                label: 'Save Lead to DB',
                description: 'Log enriched leads to MongoDB.',
                config: {
                  collectionName: 'enriched_leads',
                  document: {
                    email: '{{trigger.email}}',
                    interestTags: '{{nodes.gemini-2.output}}',
                    mood: '{{nodes.gemini-1.output}}'
                  }
                }
              }
            }
          ];
          edges = [
            { id: 'edge-1', source: 'trigger-1', target: 'gemini-1', animated: true },
            { id: 'edge-2', source: 'trigger-1', target: 'gemini-2', animated: true },
            { id: 'edge-3', source: 'gemini-1', target: 'db-1', animated: true },
            { id: 'edge-4', source: 'gemini-2', target: 'db-1', animated: true }
          ];
          break;

        case 'template_social_media':
          name = 'Weekly Social Poster';
          description = 'Schedule posts and generate summaries using Gemini.';
          nodes = [
            {
              id: 'trigger-1',
              type: 'scheduleTrigger',
              position: { x: 100, y: 200 },
              data: {
                label: 'Weekly Schedule',
                description: 'Trigger every Friday.',
                config: { scheduleType: 'interval', interval: 10080 }
              }
            },
            {
              id: 'gemini-1',
              type: 'geminiNode',
              position: { x: 380, y: 200 },
              data: {
                label: 'Tweet Drafter',
                description: 'Draft social posts using Gemini.',
                config: {
                  task: 'generate',
                  prompt: 'Draft an engaging promotional tweet (under 280 chars) announcing our new project update: "FlowGenius AI is now open source with direct React Flow visual mapping."'
                }
              }
            },
            {
              id: 'http-1',
              type: 'httpNode',
              position: { x: 660, y: 200 },
              data: {
                label: 'Queue Social Post',
                description: 'Post draft payload to social manager webhook.',
                config: {
                  url: 'https://api.buffer.com/v1/updates/create',
                  method: 'POST',
                  headers: { 'Content-Type': 'application/json' },
                  body: '{\n  "tweet": "{{nodes.gemini-1.output}}"\n}'
                }
              }
            }
          ];
          edges = [
            { id: 'edge-1', source: 'trigger-1', target: 'gemini-1', animated: true },
            { id: 'edge-2', source: 'gemini-1', target: 'http-1', animated: true }
          ];
          break;

        case 'template_meeting_notes':
        default:
          name = 'Meeting Note Refiner';
          description = 'Pass transcripts through Gemini and email them out.';
          nodes = [
            {
              id: 'trigger-1',
              type: 'manualTrigger',
              position: { x: 100, y: 200 },
              data: {
                label: 'Transcript Trigger',
                description: 'Enter raw conversation transcript.',
                config: {
                  payload: {
                    meetingTitle: 'FlowGenius Sync',
                    transcript: 'Sukumar: We need to build the frontend. Alex: I will set up the Express routes and JWT auth by tonight. Sukumar: Great, I will handle the React Flow canvas tomorrow.'
                  }
                }
              }
            },
            {
              id: 'gemini-1',
              type: 'geminiNode',
              position: { x: 380, y: 200 },
              data: {
                label: 'Action Item Refiner',
                description: 'Extract tasks and assignees.',
                config: {
                  task: 'summarize',
                  prompt: 'Analyze the following meeting transcript. Format as a bulleted list of Action Items and who is assigned to each: "{{trigger.transcript}}"'
                }
              }
            },
            {
              id: 'email-1',
              type: 'emailNode',
              position: { x: 660, y: 200 },
              data: {
                label: 'Email Action Items',
                description: 'Send action item list to the team.',
                config: {
                  to: 'team@company.com',
                  subject: 'Action Items: {{trigger.meetingTitle}}',
                  body: 'Team, here are the follow-up tasks from today\'s meeting:\n\n{{nodes.gemini-1.output}}'
                }
              }
            }
          ];
          edges = [
            { id: 'edge-1', source: 'trigger-1', target: 'gemini-1', animated: true },
            { id: 'edge-2', source: 'gemini-1', target: 'email-1', animated: true }
          ];
          break;
      }

      // Hit API to create new workflow populated with template
      const response = await api.post('/workflows', { name, description, nodes, edges });
      const newWf = response.data.workflow;
      handleNavigateToBuilder(newWf._id);
    } catch (err) {
      console.error('Template copy failed:', err);
      // local mockup fallback
      handleNavigateToBuilder();
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen w-full flex flex-col items-center justify-center bg-black text-gray-400">
        <Loader2 className="w-10 h-10 text-indigo-500 animate-spin mb-4 animate-pulse-glow" />
        <span className="text-xs uppercase font-extrabold tracking-widest">Booting FlowGenius AI...</span>
      </div>
    );
  }

  // Auth Gate
  if (!user) {
    return authScreen === 'login' ? (
      <Login 
        onNavigateToRegister={() => setAuthScreen('register')} 
        onSuccess={() => setActiveTab('dashboard')} 
      />
    ) : (
      <Register 
        onNavigateToLogin={() => setAuthScreen('login')} 
        onSuccess={() => setActiveTab('dashboard')} 
      />
    );
  }

  // If activeTab is 'builder', render the builder full screen without default navigations
  if (activeTab === 'builder') {
    return (
      <WorkflowBuilder
        workflowId={editingWorkflowId}
        onNavigateBack={() => setActiveTab('dashboard')}
      />
    );
  }

  const navItems = [
    { id: 'dashboard' as const, label: 'Dashboard', icon: LayoutDashboard },
    { id: 'logs' as const, label: 'Execution Logs', icon: Terminal },
    { id: 'profile' as const, label: 'Settings & Keys', icon: User },
  ];

  return (
    <div className="min-h-screen w-full flex bg-[#09090C] text-gray-200">
      
      {/* Sidebar - Desktop */}
      <aside className="hidden md:flex flex-col w-64 bg-neutral-950 border-r border-neutral-900 justify-between shrink-0 p-5 h-screen">
        <div className="space-y-8">
          {/* Logo brand */}
          <div className="flex items-center gap-3 px-2">
            <div className="w-9 h-9 rounded-lg bg-gradient-to-tr from-indigo-500 via-purple-500 to-pink-500 flex items-center justify-center shadow-md shadow-indigo-500/10">
              <span className="text-sm font-black text-white">FG</span>
            </div>
            <div>
              <h2 className="text-md font-extrabold text-white tracking-tight leading-none">FlowGenius AI</h2>
              <span className="text-[9px] text-gray-500 font-semibold uppercase tracking-wider">Automation Panel</span>
            </div>
          </div>

          {/* Navigation Links */}
          <nav className="space-y-1.5">
            {navItems.map((item) => {
              const Icon = item.icon;
              return (
                <button
                  key={item.id}
                  onClick={() => setActiveTab(item.id)}
                  className={`w-full flex items-center gap-3 px-3.5 py-3 rounded-xl text-xs font-semibold tracking-wide transition-all ${
                    activeTab === item.id
                      ? 'bg-indigo-600 text-white shadow-lg shadow-indigo-600/15'
                      : 'text-gray-400 hover:text-white hover:bg-neutral-900/50'
                  }`}
                >
                  <Icon className="w-4 h-4" />
                  {item.label}
                </button>
              );
            })}
          </nav>
        </div>

        {/* User profile dock at bottom */}
        <div className="space-y-4 border-t border-neutral-900 pt-5">
          <div className="flex items-center gap-3 px-1.5">
            <img
              src={user.avatar || `https://api.dicebear.com/7.x/initials/svg?seed=${user.name}`}
              alt={user.name}
              className="w-10 h-10 rounded-full bg-neutral-900 object-cover border border-neutral-800"
            />
            <div className="min-w-0 flex-1">
              <h4 className="text-xs font-bold text-white truncate">{user.name}</h4>
              <p className="text-[10px] text-gray-500 truncate">{user.email}</p>
            </div>
          </div>

          <button
            onClick={logout}
            className="w-full flex items-center justify-center gap-2 px-3 py-2.5 text-xs font-semibold text-gray-400 hover:text-red-400 hover:bg-red-500/5 border border-transparent hover:border-red-500/10 rounded-xl transition-all"
          >
            <LogOut className="w-4 h-4" />
            Sign Out
          </button>
        </div>
      </aside>

      {/* Mobile Header Bar */}
      <div className="flex-1 flex flex-col min-w-0 h-screen overflow-hidden">
        <header className="md:hidden flex items-center justify-between px-6 py-4 bg-neutral-950 border-b border-neutral-900 shrink-0">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-tr from-indigo-500 via-purple-500 to-pink-500 flex items-center justify-center">
              <span className="text-xs font-black text-white">FG</span>
            </div>
            <h2 className="text-sm font-extrabold text-white">FlowGenius</h2>
          </div>
          <button
            onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            className="p-2 bg-neutral-900 border border-neutral-800 text-gray-400 rounded-lg"
          >
            {mobileMenuOpen ? <X className="w-4 h-4" /> : <Menu className="w-4 h-4" />}
          </button>
        </header>

        {/* Mobile Menu Panel */}
        {mobileMenuOpen && (
          <div className="md:hidden fixed inset-0 top-[65px] bg-[#09090C] z-30 flex flex-col justify-between p-6">
            <nav className="space-y-2">
              {navItems.map((item) => {
                const Icon = item.icon;
                return (
                  <button
                    key={item.id}
                    onClick={() => {
                      setActiveTab(item.id);
                      setMobileMenuOpen(false);
                    }}
                    className={`w-full flex items-center gap-3 p-4 rounded-xl text-sm font-semibold tracking-wide transition-all ${
                      activeTab === item.id
                        ? 'bg-indigo-600 text-white'
                        : 'text-gray-400 hover:text-white bg-neutral-900/40'
                    }`}
                  >
                    <Icon className="w-5 h-5" />
                    {item.label}
                  </button>
                );
              })}
            </nav>
            <div className="space-y-4 border-t border-neutral-900 pt-6">
              <div className="flex items-center gap-3">
                <img
                  src={user.avatar}
                  alt={user.name}
                  className="w-10 h-10 rounded-full bg-neutral-950 object-cover border"
                />
                <div>
                  <h4 className="text-sm font-bold text-white">{user.name}</h4>
                  <p className="text-xs text-gray-500">{user.email}</p>
                </div>
              </div>
              <button
                onClick={() => {
                  setMobileMenuOpen(false);
                  logout();
                }}
                className="w-full py-3 bg-red-950/20 border border-red-500/20 text-red-400 rounded-xl text-xs font-bold flex items-center justify-center gap-2"
              >
                <LogOut className="w-4 h-4" />
                Sign Out
              </button>
            </div>
          </div>
        )}

        {/* Main Content Area */}
        <main className="flex-1 overflow-y-auto bg-[#09090C]">
          {activeTab === 'dashboard' && (
            <Dashboard
              onNavigateToBuilder={handleNavigateToBuilder}
              onNavigateToLogs={() => setActiveTab('logs')}
              onNavigateToTemplates={handleNavigateToTemplates}
            />
          )}
          {activeTab === 'logs' && (
            <Logs 
              workflows={[]} 
              onNavigateToBuilder={handleNavigateToBuilder} 
            />
          )}
          {activeTab === 'profile' && <Profile />}
        </main>
      </div>
    </div>
  );
};

export default function App() {
  return <AppContent />;
}
