import { Request, Response } from 'express';
import { Template } from '../models/Template';

export const listTemplates = async (_req: Request, res: Response) => {
  try {
    const templates = await Template.find({});
    return res.status(200).json({ templates });
  } catch (error: any) {
    console.error('List templates error:', error);
    return res.status(500).json({ message: 'Server error.', error: error.message });
  }
};

export const seedDefaultTemplates = async () => {
  try {
    const count = await Template.countDocuments();
    if (count > 0) {
      console.log('Templates already seeded.');
      return;
    }

    const defaultTemplates = [
      {
        name: 'Email Summarizer',
        description: 'Trigger on incoming Gmail and generate an AI summary using Gemini.',
        category: 'AI Productivity',
        icon: 'mail',
        nodes: [
          {
            id: 'trigger-1',
            type: 'manualTrigger',
            position: { x: 100, y: 200 },
            data: {
              label: 'Manual Gmail Trigger',
              description: 'Pass incoming email data fields.',
              config: {
                payload: {
                  sender: 'newsletter@techweekly.com',
                  subject: 'Weekly AI Innovations Newsletter',
                  body: 'Artificial Intelligence has seen major breakthroughs this week. OpenAI released GPT-5, Anthropic upgraded Claude with longer context, and Google integrated Gemini natively into Android system kernels.'
                }
              }
            }
          },
          {
            id: 'gemini-1',
            type: 'geminiNode',
            position: { x: 380, y: 200 },
            data: {
              label: 'Gemini AI Summary',
              description: 'Generate concise summaries using Gemini AI.',
              config: {
                task: 'summarize',
                prompt: 'Summarize the following email newsletter content. Extract main breakthroughs: "{{trigger.body}}"'
              }
            }
          },
          {
            id: 'email-1',
            type: 'emailNode',
            position: { x: 660, y: 200 },
            data: {
              label: 'Send Summary Email',
              description: 'Send the summarized newsletter text.',
              config: {
                to: 'me@company.com',
                subject: 'AI Newsletter Summary: {{trigger.subject}}',
                body: 'Here is the summary generated by FlowGenius AI:\n\n{{nodes.gemini-1.output}}'
              }
            }
          }
        ],
        edges: [
          { id: 'edge-1', source: 'trigger-1', target: 'gemini-1', animated: true },
          { id: 'edge-2', source: 'gemini-1', target: 'email-1', animated: true }
        ]
      },
      {
        name: 'Lead Enrichment Sync',
        description: 'Receive webhook payloads, extract keywords and sentiment, and log to Google Sheets.',
        category: 'Marketing',
        icon: 'shield',
        nodes: [
          {
            id: 'trigger-1',
            type: 'webhookTrigger',
            position: { x: 100, y: 200 },
            data: {
              label: 'Webhook Lead Trigger',
              description: 'Receive payload from signup form.',
              config: {}
            }
          },
          {
            id: 'gemini-1',
            type: 'geminiNode',
            position: { x: 380, y: 100 },
            data: {
              label: 'Sentiment Evaluator',
              description: 'Analyze sign-up interest sentiment.',
              config: {
                task: 'sentiment',
                prompt: 'Analyze lead review: "{{trigger.comments}}"'
              }
            }
          },
          {
            id: 'gemini-2',
            type: 'geminiNode',
            position: { x: 380, y: 300 },
            data: {
              label: 'Keywords Extractor',
              description: 'Extract product interest tags.',
              config: {
                task: 'keywords',
                prompt: 'Extract interest tags: "{{trigger.comments}}"'
              }
            }
          },
          {
            id: 'db-1',
            type: 'dbNode',
            position: { x: 680, y: 200 },
            data: {
              label: 'Save Lead to DB',
              description: 'Log enriched leads to MongoDB.',
              config: {
                collectionName: 'enriched_leads',
                document: {
                  email: '{{trigger.email}}',
                  interestTags: '{{nodes.gemini-2.output}}',
                  mood: '{{nodes.gemini-1.output}}'
                }
              }
            }
          }
        ],
        edges: [
          { id: 'edge-1', source: 'trigger-1', target: 'gemini-1', animated: true },
          { id: 'edge-2', source: 'trigger-1', target: 'gemini-2', animated: true },
          { id: 'edge-3', source: 'gemini-1', target: 'db-1', animated: true },
          { id: 'edge-4', source: 'gemini-2', target: 'db-1', animated: true }
        ]
      },
      {
        name: 'Social Media Creator',
        description: 'Schedule a trigger, generate a blog summary, and queue standard social draft payloads.',
        category: 'Social Media',
        icon: 'share',
        nodes: [
          {
            id: 'trigger-1',
            type: 'scheduleTrigger',
            position: { x: 100, y: 200 },
            data: {
              label: 'Weekly Schedule',
              description: 'Trigger every Friday.',
              config: { scheduleType: 'interval', interval: 10080 }
            }
          },
          {
            id: 'gemini-1',
            type: 'geminiNode',
            position: { x: 380, y: 200 },
            data: {
              label: 'Tweet Drafter',
              description: 'Draft social posts using Gemini.',
              config: {
                task: 'generate',
                prompt: 'Draft an engaging promotional tweet (under 280 chars) announcing our new project update: "FlowGenius AI is now open source with direct React Flow visual mapping."'
              }
            }
          },
          {
            id: 'http-1',
            type: 'httpNode',
            position: { x: 660, y: 200 },
            data: {
              label: 'Queue Social Post',
              description: 'Post draft payload to social manager webhook.',
              config: {
                url: 'https://api.buffer.com/v1/updates/create',
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: '{\n  "tweet": "{{nodes.gemini-1.output}}"\n}'
              }
            }
          }
        ],
        edges: [
          { id: 'edge-1', source: 'trigger-1', target: 'gemini-1', animated: true },
          { id: 'edge-2', source: 'gemini-1', target: 'http-1', animated: true }
        ]
      },
      {
        name: 'Meeting Note Refiner',
        description: 'Pass transcript details through Gemini to format action items and email them out.',
        category: 'Collaboration',
        icon: 'text',
        nodes: [
          {
            id: 'trigger-1',
            type: 'manualTrigger',
            position: { x: 100, y: 200 },
            data: {
              label: 'Transcript Trigger',
              description: 'Enter raw conversation transcript.',
              config: {
                payload: {
                  meetingTitle: 'FlowGenius Sync',
                  transcript: 'Sukumar: We need to build the frontend. Alex: I will set up the Express routes and JWT auth by tonight. Sukumar: Great, I will handle the React Flow canvas tomorrow.'
                }
              }
            }
          },
          {
            id: 'gemini-1',
            type: 'geminiNode',
            position: { x: 380, y: 200 },
            data: {
              label: 'Action Item Refiner',
              description: 'Extract tasks and assignees.',
              config: {
                task: 'summarize',
                prompt: 'Analyze the following meeting transcript. Format as a bulleted list of Action Items and who is assigned to each: "{{trigger.transcript}}"'
              }
            }
          },
          {
            id: 'email-1',
            type: 'emailNode',
            position: { x: 660, y: 200 },
            data: {
              label: 'Email Action Items',
              description: 'Send action item list to the team.',
              config: {
                to: 'team@company.com',
                subject: 'Action Items: {{trigger.meetingTitle}}',
                body: 'Team, here are the follow-up tasks from today\'s meeting:\n\n{{nodes.gemini-1.output}}'
              }
            }
          }
        ],
        edges: [
          { id: 'edge-1', source: 'trigger-1', target: 'gemini-1', animated: true },
          { id: 'edge-2', source: 'gemini-1', target: 'email-1', animated: true }
        ]
      }
    ];

    await Template.insertMany(defaultTemplates);
    console.log('Templates seeded successfully!');
  } catch (error) {
    console.error('Error seeding templates:', error);
  }
};
